### ISSUE TITLE
ウインドウ境界の問題

### ISSUE THREAD

**Issue by metahoi** [saasan/PSO2Utility#1]
Win10環境においてPSO2Utilityから最小化及びウィンドウ位置有効化を行うと
NGSのウインドウの4辺に一回り大きな領域が出てしまいます
おそらくWin7基準のウインドウの枠を前提とした範囲指定を行ってしまった結果かと思われます
すでに2020年1月以降からPSO2およびNGSはWin7でのサポートは除外されていますので
この部分を何とかしていただけるとより使いやすくなると思われます

何卒前向きな検討をよろしくお願いいたします
![PSO2ウインドウモード0001](https://user-images.githubusercontent.com/89115489/129829407-54edcb92-b622-4fc6-894b-17194ed091f1.png)

**Comment by saasan** [comment]
最小化ボタンを表示時にウィンドウ内に枠が表示される問題はv1.2で修正しました。
ウィンドウ位置復元時の問題はいろいろと試しましたが直りませんでした。
